package runtime

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path"
	"regexp"
	goruntime "runtime"
	"sort"
	"strconv"
	"strings"

	"github.com/reddywritescode/agentpop/internal/model"
)

var ErrNotFound = errors.New("runtime sandbox not found")

// imageRefPattern constrains template image references so they are safe to
// pass to the container runtime and to derive filesystem paths from.
var imageRefPattern = regexp.MustCompile(`^[a-z0-9][a-z0-9._/-]{0,200}(:[A-Za-z0-9._-]{1,64})?$`)

func ValidateImageRef(ref string) error {
	if !imageRefPattern.MatchString(ref) {
		return fmt.Errorf("invalid image reference %q", ref)
	}
	return nil
}

func NormalizeGuestFilePath(value string) (string, error) {
	cleaned := path.Clean(strings.TrimSpace(value))
	if cleaned == "/workspace" || !strings.HasPrefix(cleaned, "/workspace/") {
		return "", errors.New("path must name a file under /workspace")
	}
	return cleaned, nil
}

type Driver interface {
	Name() string
	HostInfo(context.Context) model.HostInfo
	Create(context.Context, model.RuntimeCreateRequest) (model.RuntimeSandbox, error)
	Update(context.Context, string, model.RuntimeUpdateRequest) (model.RuntimeSandbox, error)
	SetSecrets(context.Context, string, model.RuntimeSecretsRequest) error
	Exec(context.Context, string, model.ExecRequest) (model.ExecResult, error)
	WriteFile(context.Context, string, string, []byte) error
	ReadFile(context.Context, string, string) ([]byte, error)
	Pause(context.Context, string) (model.RuntimeSandbox, error)
	Resume(context.Context, string) (model.RuntimeSandbox, error)
	Destroy(context.Context, string) error
	Inspect(context.Context, string) (model.RuntimeSandbox, error)
	// Commit snapshots a running build sandbox into an immutable, reusable
	// image (Docker image or Firecracker template rootfs).
	Commit(context.Context, string, model.RuntimeCommitRequest) (model.RuntimeImage, error)
	// RemoveImage deletes a previously committed template image.
	RemoveImage(context.Context, string) error
}

func renderSecretProfile(secrets map[string]string) ([]byte, error) {
	keys := make([]string, 0, len(secrets))
	for key := range secrets {
		if !validEnvironmentKey(key) {
			return nil, fmt.Errorf("invalid secret environment key %q", key)
		}
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var profile strings.Builder
	profile.WriteString("# Generated by AgentPop. Values are write-only in the control plane.\n")
	for _, key := range keys {
		profile.WriteString("export " + key + "=" + shellQuote(secrets[key]) + "\n")
	}
	return []byte(profile.String()), nil
}

func hostMemoryMB() int64 {
	data, err := os.ReadFile("/proc/meminfo")
	if err != nil {
		return 0
	}
	for _, line := range strings.Split(string(data), "\n") {
		fields := strings.Fields(line)
		if len(fields) >= 2 && fields[0] == "MemTotal:" {
			kib, parseErr := strconv.ParseInt(fields[1], 10, 64)
			if parseErr == nil {
				return kib / 1024
			}
		}
	}
	return 0
}

type Config struct {
	Mode              string
	HostID            string
	HostName          string
	Region            string
	HostSSHCommand    string
	DockerImage       string
	DockerBinary      string
	SSHPrivateKeyPath string
	FirecrackerBinary string
	JailerBinary      string
	KernelImagePath   string
	RootFSPath        string
	StateDirectory    string
}

func NewDriver(ctx context.Context, cfg Config) (Driver, error) {
	mode := strings.ToLower(strings.TrimSpace(cfg.Mode))
	if mode == "" || mode == "auto" {
		if goruntime.GOOS == "linux" && fileExists("/dev/kvm") && commandWorks(ctx, cfg.FirecrackerBinary, "--version") {
			mode = "firecracker"
		} else if commandWorks(ctx, cfg.DockerBinary, "info") {
			mode = "docker"
		} else {
			return nil, errors.New("no runtime available: start Docker Desktop locally or run the host agent on Linux with /dev/kvm and Firecracker")
		}
	}
	switch mode {
	case "docker":
		return NewDockerDriver(cfg)
	case "firecracker":
		return NewFirecrackerDriver(cfg)
	default:
		return nil, fmt.Errorf("unsupported runtime driver %q", cfg.Mode)
	}
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func commandWorks(ctx context.Context, binary string, args ...string) bool {
	if strings.TrimSpace(binary) == "" {
		return false
	}
	cmd := exec.CommandContext(ctx, binary, args...)
	return cmd.Run() == nil
}
