substitutions:
  _REGION: us-west1
  _REPOSITORY: agentpop
  _TAG: dev

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - deploy/docker/web.Dockerfile
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/web:${_TAG}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - deploy/docker/control-plane.Dockerfile
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/control-plane:${_TAG}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - deploy/docker/connector-broker.Dockerfile
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/connector-broker:${_TAG}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/web:${_TAG}
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/control-plane:${_TAG}
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/connector-broker:${_TAG}

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/web:${_TAG}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/control-plane:${_TAG}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/connector-broker:${_TAG}

options:
  logging: CLOUD_LOGGING_ONLY
